version: "3.8"
services:
  scoretrak:
    image: l1ghtman/scoretrak:latest
    volumes:
      - ../../deployments/:/deployments
    depends_on:
      - db-init
    ports:
      - "33333:33333"
    command: ./master -config /deployments/docker-standalone/config.yml

  cockroachdb-1:
    container_name: cockroachdb-1
    image: cockroachdb/cockroach:latest
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      default:
        aliases:
          - cockroach

  db-init:
    depends_on:
      - cockroachdb-1
    image: cockroachdb/cockroach:latest
    command: sql --execute="CREATE DATABASE IF NOT EXISTS scoretrak;" --insecure --host cockroach

networks:
  default:
    attachable: yes


