version: "3.8"
services:
  scoretrak:
    build:
      context: ../..
      dockerfile: deployments/master/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db-init
      - nsqd
    ports:
      - "33333:33333" #In case there is a web component for scoretrak, this could be commented out
    command: -config deployments/master-nsq/config.yml
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  cockroachdb-1:
    image: cockroachdb/cockroach:latest --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      default:
        aliases:
          - cockroach

  cockroachdb-2:
    image: cockroachdb/cockroach:latest --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      default:
        aliases:
          - cockroach

  cockroachdb-3:
    image: cockroachdb/cockroach:latest --join=cockroachdb-1:26257,cockroachdb-2:26257,cockroachdb-3:26257 --cache=.25 --max-sql-memory=.25 --logtostderr
    command: start --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      default:
        aliases:
          - cockroach

  db-init:
    depends_on:
      - cockroachdb-1
      - cockroachdb-2
      - cockroachdb-3
    image: cockroachdb/cockroach:latest
    volumes:
      - ../../scripts:/scripts
    entrypoint: "/bin/bash"
    command: /scripts/init_db.sh


  nsqlookupd:
    image: nsqio/nsq
    networks:
      - default
    command: /nsqlookupd
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

  nsqd:
    image: nsqio/docker-nsq
    networks:
      - default
    command: /nsqd --broadcast-address=nsqd --lookupd-tcp-address=nsqlookupd:4160
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
    depends_on:
      - nsqlookupd

  nsqadmin:
    image: claudiomastrapasqua/docker-nsq
    hostname: nsqadmin
    ports:
      - "4171:4171"
    networks:
      - default
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    deploy:
      replicas: 1
    depends_on:
      - nsqlookupd

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000"
    networks:
      - default
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  default:
    attachable: yes

