apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    name: scoretrak
    namespace: default
roleRef:
  kind: ClusterRole
  name: scoretrak
  apiGroup: rbac.authorization.k8s.io