apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: scoretrak
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "delete", "list", "create"]